# Generated by Django 3.1 on 2020-12-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iventory',
            new_name='inventory',
        ),
    ]
